### ISSUE TITLE
Problem launching the game

### ISSUE THREAD

**Issue by martsrzx91** [Xman1109/More_Ammo#10]
Some compability issue.
![image](https://github.com/user-attachments/assets/5e0686b9-7c87-48e2-a22a-9f04d287fb75)

**Comment by Xman1109** [comment]
Would you mind looking at which mod in your mod pack conflicts with More Ammo?

**Comment by martsrzx91** [comment]
could be this one 
![image](https://github.com/user-attachments/assets/a4053548-cb75-44e1-a014-b6d5505e3df4)
https://mods.factorio.com/mod/StarsWithSakura?from=updated

**Comment by Xman1109** [comment]
I have fixed the issue on my end, bug can't seem to get the other mod working, so please notify him about it, because I can't fix his code.

**Comment by martsrzx91** [comment]
I tried to contact him too, but couldn't find github page

**Comment by Xman1109** [comment]
Maybe you should try to leave a comment under one of his mods on the modportal

**Comment by martsrzx91** [comment]
Did that ;)

**Comment by Deadexow** [comment]
Oh，god，I am the starswithsakura author，the starswithsakura have own military system，needn't add any more other military mods
But，I wil try to fix it！oh god！there is so many bugs，BOOOOOOOOOOOM！

**Comment by Deadexow** [comment]
And have own damage algorithm.
