### ISSUE TITLE
Compatibility with Distant Missfires

### ISSUE THREAD

**Issue by FluffyDiscord** [Xman1109/More_Ammo#11]
**Describe the bug**
This mod is not compatible with the beloved Distant Missfires mod. By the discussion on their side, it looks like they cannot do anything about it. Would it be possible to support that mod?

https://mods.factorio.com/mod/distant-misfires/discussion/6704b4a46d95731a41f1dd3a

**To Reproduce**
---

**Expected behavior**
Be compatible

**Screenshots**
---

**Additional context**
---

**Comment by Xman1109** [comment]
His/Her code looks very complicated, I'll give it a shot, but can't promise anything.

**Comment by Xman1109** [comment]
As of version 1.5.20 this issue should be fixed, feel free to reopen this if you encounter this error message again.

**Comment by FluffyDiscord** [comment]
Will test later today, thank you!
