### ISSUE TITLE
Missing recipes for extended mags

### ISSUE THREAD

**Issue by MusicManiac** [Xman1109/More_Ammo#2]
There are no recipes for some extended mags. For example, you can craft empty extended mag for normal or AP ammo but you can't fill them up. Tested with only this mod + FNEI mod enabled.
FNEI indicates they require no research to be able to be crafted, and there IS recipe for them but they simply do not appear?

Screenshot of sandbox with all tech researched but cheat mode is off. Missing recepies for normal, AP and uranium rounds.
![image](https://github.com/Xman1109/More_Ammo/assets/14209235/318de0a4-bb11-4c6f-bb71-4e07f59209a5)

**Comment by Xman1109** [comment]
Should be fixed now, the ones that were missing are now accessible through the "Extended Advanced Ammunition" tech.

If not, then reopen the Issue and I will be happy to assist you further.
